### ISSUE TITLE
报错：创建Aria任务失败连接断开

### ISSUE THREAD

**Issue by MrWrh** [SeeDLL-Docker/Aliyunpan#1]
错误日志：

24 15:48:35 : danger : AriaAddUrl Cannot read properties of undefined (reading '2') 
//== Error ==//
 Cannot read properties of undefined (reading '2') 
//== Stack ===//
 TypeError: Cannot read properties of undefined (reading '2')
    at AriaAddUrl (file:///opt/xbyyunpan/resources/app.asar/dist/index.js:140:12732)
    at async DownDAL.aSpeedEvent (file:///opt/xbyyunpan/resources/app.asar/dist/index.js:140:19168)
24 15:40:24 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ae.emit (file:///opt/xbyyunpan/resources/app.asar/dist/index.js:121:60559)
    at he.onerror (file:///opt/xbyyunpan/resources/app.asar/dist/index.js:121:68380)
24 15:40:24 : danger : Uncaught Error: Unhandled error. (undefined)
24 15:40:24 : danger : onerror
24 15:40:23 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ae.emit (file:///opt/xbyyunpan/resources/app.asar/dist/index.js:121:60559)
    at he.onerror (file:///opt/xbyyunpan/resources/app.asar/dist/index.js:121:68380)
24 15:40:23 : danger : Uncaught Error: Unhandled error. (undefined)
24 15:40:23 : danger : onerror
24 15:40:22 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ae.emit (file:///opt/xbyyunpan/resources/app.asar/dist/index.js:121:60559)
    at he.onerror (file:///opt/xbyyunpan/resources/app.asar/dist/index.js:121:68380)
24 15:40:22 : danger : Uncaught Error: Unhandled error. (undefined)
24 15:40:22 : danger : onerror
24 15:40:21 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ae.emit (file:///opt/xbyyunpan/resources/app.asar/dist/index.js:121:60559)
    at he.onerror (file:///opt/xbyyunpan/resources/app.asar/dist/index.js:121:68380)
24 15:40:21 : danger : Uncaught Error: Unhandled error. (undefined)
24 15:40:21 : danger : onerror
24 15:40:20 : danger : onerror 
//== Error ==//
 Unhandled error. (undefined) 
//== Stack ===//
 Error: Unhandled error. (undefined)
    at ae.emit (file:///opt/xbyyunpan/resources/app.asar/dist/index.js:121:60559)
    at he.onerror (file:///opt/xbyyunpan/resources/app.asar/dist/index.js:121:68380)
24 15:40:20 : danger : Uncaught Error: Unhandled error. (undefined)
24 15:40:20 : danger : onerror
24 15:40:03 : warning : HttpError4 status=400 code=InvalidCode message=Request failed with status code 400
24 15:40:03 : warning : HttpError4 status=400 code=InvalidCode message=Request failed with status code 400
24 15:40:03 : warning : HttpError4 status=400 code=InvalidCode message=Request failed with status code 400
24 15:40:03 : warning : HttpError4 status=400 code=InvalidCode message=Request failed with status code 400
24 15:40:03 : warning : HttpError4 status=400 code=InvalidCode message=Request failed with status code 400
24 15:40:03 : warning : HttpError4 status=400 code=InvalidCode message=Request failed with status code 400
24 15:40:03 : warning : HttpError4 status=400 code=InvalidCode message=Request failed with status code 400
24 15:39:32 : success : 小白羊启动

**Comment by MononeV** [comment]
我另外建了一個Aria2用遠程了

**Comment by SeeDLL** [comment]
会不会是配置的aria2的连接有问题？就是有什么特殊字符之类的？关于其他程序问题的话，你可以到小白羊作者那边提交下issues看看呢，我这边只是用自动脚本下载打包的

**Comment by MononeV** [comment]
倒不如說不知道怎麼配置

> 容器中已经自带了一个 Aria2c ，路径是：/usr/bin/aria2c 。
> 
> 容器中已经自带了一个最基础的 Aria2c 的配置文件，路径是：/opt/Aria2/config.json ，若需要更多自定义设置，请自行修改后放到 config 目录中并在程序中自行设置指定 Aria2c 的配置文件。

這裡指的是哪裡的路徑？是否需要挂載？

**Comment by SeeDLL** [comment]
这肯定需要挂载的呀。

在说明中已经有举例说明的：
创建 aliyunpan 容器

 docker create \
    --name=aliyunpan \
    -p 5800:5800 \
    -p 5900:5900 \
    -v /配置文件位置:/config \
    -v /下载位置:/config/download \
    -v /dev/shm/xbyyunpan:/dev/shm \
    --restart unless-stopped \
    seedll/aliyunpan:latest


-v /配置文件位置:/config \   ，你在这个目录中，放置你的ALYunPan的相关配置，至于 aria2c 的配置，那个可以先不用管了。
